/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RedemptionOption = IDL.Record({
  'id' : IDL.Nat,
  'pointsRequired' : IDL.Nat,
  'restrictions' : IDL.Text,
  'fees' : IDL.Float64,
  'cashValue' : IDL.Float64,
  'type' : IDL.Variant({
    'other' : IDL.Null,
    'statementCredit' : IDL.Null,
    'travelPortal' : IDL.Null,
    'giftCard' : IDL.Null,
    'transferToPartner' : IDL.Null,
  }),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RewardPoints = IDL.Record({
  'id' : IDL.Nat,
  'balance' : IDL.Nat,
  'options' : IDL.Vec(RedemptionOption),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addRedemptionOption' : IDL.Func([IDL.Nat, RedemptionOption], [IDL.Nat], []),
  'addRewardProfile' : IDL.Func(
      [IDL.Nat, IDL.Vec(RedemptionOption)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRewardProfiles' : IDL.Func([], [IDL.Vec(RewardPoints)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RedemptionOption = IDL.Record({
    'id' : IDL.Nat,
    'pointsRequired' : IDL.Nat,
    'restrictions' : IDL.Text,
    'fees' : IDL.Float64,
    'cashValue' : IDL.Float64,
    'type' : IDL.Variant({
      'other' : IDL.Null,
      'statementCredit' : IDL.Null,
      'travelPortal' : IDL.Null,
      'giftCard' : IDL.Null,
      'transferToPartner' : IDL.Null,
    }),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RewardPoints = IDL.Record({
    'id' : IDL.Nat,
    'balance' : IDL.Nat,
    'options' : IDL.Vec(RedemptionOption),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addRedemptionOption' : IDL.Func(
        [IDL.Nat, RedemptionOption],
        [IDL.Nat],
        [],
      ),
    'addRewardProfile' : IDL.Func(
        [IDL.Nat, IDL.Vec(RedemptionOption)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRewardProfiles' : IDL.Func([], [IDL.Vec(RewardPoints)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };