/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RedemptionOption {
  'id' : bigint,
  'pointsRequired' : bigint,
  'restrictions' : string,
  'fees' : number,
  'cashValue' : number,
  'type' : { 'other' : null } |
    { 'statementCredit' : null } |
    { 'travelPortal' : null } |
    { 'giftCard' : null } |
    { 'transferToPartner' : null },
}
export interface RewardPoints {
  'id' : bigint,
  'balance' : bigint,
  'options' : Array<RedemptionOption>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addRedemptionOption' : ActorMethod<[bigint, RedemptionOption], bigint>,
  'addRewardProfile' : ActorMethod<[bigint, Array<RedemptionOption>], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRewardProfiles' : ActorMethod<[], Array<RewardPoints>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];