/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RewardPoints {
    id: bigint;
    balance: bigint;
    options: Array<RedemptionOption>;
}
export interface RedemptionOption {
    id: bigint;
    pointsRequired: bigint;
    restrictions: string;
    fees: number;
    cashValue: number;
    type: Variant_other_statementCredit_travelPortal_giftCard_transferToPartner;
}
export interface UserProfile {
    name: string;
}
export interface Transaction {
    id: bigint;
    date: string;
    currency: Currency;
    merchant: string;
    notes: string;
    category: string;
    cardLabel: string;
    amount: number;
    rawDescription: string;
}
export enum Currency {
    BTC = "BTC",
    ETH = "ETH",
    EUR = "EUR",
    ICP = "ICP",
    RUB = "RUB",
    USD = "USD",
    XMR = "XMR",
    FIAT = "FIAT"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_other_statementCredit_travelPortal_giftCard_transferToPartner {
    other = "other",
    statementCredit = "statementCredit",
    travelPortal = "travelPortal",
    giftCard = "giftCard",
    transferToPartner = "transferToPartner"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRedemptionOption(rewardId: bigint, newOption: RedemptionOption): Promise<bigint>;
    addRewardProfile(balance: bigint, options: Array<RedemptionOption>): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bulkImportTransactions(transactions: Array<Transaction>): Promise<void>;
    createTransaction(date: string, merchant: string, amount: number, currency: Currency, category: string, cardLabel: string, notes: string, rawDescription: string): Promise<bigint>;
    deleteTransaction(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getRewardProfiles(): Promise<Array<RewardPoints>>;
    getTransactions(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTransaction(id: bigint, updatedTransaction: Transaction): Promise<void>;
}
import type { Currency as _Currency, RedemptionOption as _RedemptionOption, RewardPoints as _RewardPoints, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRedemptionOption(arg0: bigint, arg1: RedemptionOption): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRedemptionOption(arg0, to_candid_RedemptionOption_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRedemptionOption(arg0, to_candid_RedemptionOption_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addRewardProfile(arg0: bigint, arg1: Array<RedemptionOption>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRewardProfile(arg0, to_candid_vec_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRewardProfile(arg0, to_candid_vec_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bulkImportTransactions(arg0: Array<Transaction>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkImportTransactions(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkImportTransactions(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTransaction(arg0: string, arg1: string, arg2: number, arg3: Currency, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(arg0, arg1, arg2, to_candid_Currency_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(arg0, arg1, arg2, to_candid_Currency_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewardProfiles(): Promise<Array<RewardPoints>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardProfiles();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardProfiles();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: Transaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_Transaction_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_Transaction_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Currency_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Currency): Currency {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_RedemptionOption_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedemptionOption): RedemptionOption {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RewardPoints_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardPoints): RewardPoints {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    balance: bigint;
    options: Array<_RedemptionOption>;
}): {
    id: bigint;
    balance: bigint;
    options: Array<RedemptionOption>;
} {
    return {
        id: value.id,
        balance: value.balance,
        options: from_candid_vec_n18(_uploadFile, _downloadFile, value.options)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pointsRequired: bigint;
    restrictions: string;
    fees: number;
    cashValue: number;
    type: {
        other: null;
    } | {
        statementCredit: null;
    } | {
        travelPortal: null;
    } | {
        giftCard: null;
    } | {
        transferToPartner: null;
    };
}): {
    id: bigint;
    pointsRequired: bigint;
    restrictions: string;
    fees: number;
    cashValue: number;
    type: Variant_other_statementCredit_travelPortal_giftCard_transferToPartner;
} {
    return {
        id: value.id,
        pointsRequired: value.pointsRequired,
        restrictions: value.restrictions,
        fees: value.fees,
        cashValue: value.cashValue,
        type: from_candid_variant_n21(_uploadFile, _downloadFile, value.type)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    currency: _Currency;
    merchant: string;
    notes: string;
    category: string;
    cardLabel: string;
    amount: number;
    rawDescription: string;
}): {
    id: bigint;
    date: string;
    currency: Currency;
    merchant: string;
    notes: string;
    category: string;
    cardLabel: string;
    amount: number;
    rawDescription: string;
} {
    return {
        id: value.id,
        date: value.date,
        currency: from_candid_Currency_n25(_uploadFile, _downloadFile, value.currency),
        merchant: value.merchant,
        notes: value.notes,
        category: value.category,
        cardLabel: value.cardLabel,
        amount: value.amount,
        rawDescription: value.rawDescription
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    statementCredit: null;
} | {
    travelPortal: null;
} | {
    giftCard: null;
} | {
    transferToPartner: null;
}): Variant_other_statementCredit_travelPortal_giftCard_transferToPartner {
    return "other" in value ? Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.other : "statementCredit" in value ? Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.statementCredit : "travelPortal" in value ? Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.travelPortal : "giftCard" in value ? Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.giftCard : "transferToPartner" in value ? Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.transferToPartner : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BTC: null;
} | {
    ETH: null;
} | {
    EUR: null;
} | {
    ICP: null;
} | {
    RUB: null;
} | {
    USD: null;
} | {
    XMR: null;
} | {
    FIAT: null;
}): Currency {
    return "BTC" in value ? Currency.BTC : "ETH" in value ? Currency.ETH : "EUR" in value ? Currency.EUR : "ICP" in value ? Currency.ICP : "RUB" in value ? Currency.RUB : "USD" in value ? Currency.USD : "XMR" in value ? Currency.XMR : "FIAT" in value ? Currency.FIAT : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RewardPoints>): Array<RewardPoints> {
    return value.map((x)=>from_candid_RewardPoints_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RedemptionOption>): Array<RedemptionOption> {
    return value.map((x)=>from_candid_RedemptionOption_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n23(_uploadFile, _downloadFile, x));
}
function to_candid_Currency_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): _Currency {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_RedemptionOption_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RedemptionOption): _RedemptionOption {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Transaction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Transaction): _Transaction {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pointsRequired: bigint;
    restrictions: string;
    fees: number;
    cashValue: number;
    type: Variant_other_statementCredit_travelPortal_giftCard_transferToPartner;
}): {
    id: bigint;
    pointsRequired: bigint;
    restrictions: string;
    fees: number;
    cashValue: number;
    type: {
        other: null;
    } | {
        statementCredit: null;
    } | {
        travelPortal: null;
    } | {
        giftCard: null;
    } | {
        transferToPartner: null;
    };
} {
    return {
        id: value.id,
        pointsRequired: value.pointsRequired,
        restrictions: value.restrictions,
        fees: value.fees,
        cashValue: value.cashValue,
        type: to_candid_variant_n3(_uploadFile, _downloadFile, value.type)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: string;
    currency: Currency;
    merchant: string;
    notes: string;
    category: string;
    cardLabel: string;
    amount: number;
    rawDescription: string;
}): {
    id: bigint;
    date: string;
    currency: _Currency;
    merchant: string;
    notes: string;
    category: string;
    cardLabel: string;
    amount: number;
    rawDescription: string;
} {
    return {
        id: value.id,
        date: value.date,
        currency: to_candid_Currency_n10(_uploadFile, _downloadFile, value.currency),
        merchant: value.merchant,
        notes: value.notes,
        category: value.category,
        cardLabel: value.cardLabel,
        amount: value.amount,
        rawDescription: value.rawDescription
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Currency): {
    BTC: null;
} | {
    ETH: null;
} | {
    EUR: null;
} | {
    ICP: null;
} | {
    RUB: null;
} | {
    USD: null;
} | {
    XMR: null;
} | {
    FIAT: null;
} {
    return value == Currency.BTC ? {
        BTC: null
    } : value == Currency.ETH ? {
        ETH: null
    } : value == Currency.EUR ? {
        EUR: null
    } : value == Currency.ICP ? {
        ICP: null
    } : value == Currency.RUB ? {
        RUB: null
    } : value == Currency.USD ? {
        USD: null
    } : value == Currency.XMR ? {
        XMR: null
    } : value == Currency.FIAT ? {
        FIAT: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_other_statementCredit_travelPortal_giftCard_transferToPartner): {
    other: null;
} | {
    statementCredit: null;
} | {
    travelPortal: null;
} | {
    giftCard: null;
} | {
    transferToPartner: null;
} {
    return value == Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.other ? {
        other: null
    } : value == Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.statementCredit ? {
        statementCredit: null
    } : value == Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.travelPortal ? {
        travelPortal: null
    } : value == Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.giftCard ? {
        giftCard: null
    } : value == Variant_other_statementCredit_travelPortal_giftCard_transferToPartner.transferToPartner ? {
        transferToPartner: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<RedemptionOption>): Array<_RedemptionOption> {
    return value.map((x)=>to_candid_RedemptionOption_n1(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Transaction>): Array<_Transaction> {
    return value.map((x)=>to_candid_Transaction_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
